name: CI

on: [push, pull_request]

jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - name: checkout code
      uses: actions/checkout@master
    - name: setup graphviz macos
      run: brew install graphviz
      if:  matrix.os == 'macos-latest'
    - name: setup graphviz ubuntu
      run: sudo apt-get update && sudo apt-get install graphviz --yes
      if: matrix.os == 'ubuntu-latest'
    - name: setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.x
    - name: go test
      run: go test -v -race ./...
    - name: go vet
      run: go vet ./...
